init_time <- Sys.time()

library(data.table)

cat("\tGenerating representative leases\n\t")
# read in example leases generated by inputs/leases.Rmd
leases_full <- fread("./inputs/processed/leases_full.csv")
wells <- fread("./inputs/processed/wells.csv")

# Estimate capital expenditures by well in million of dollars
# assume costs are normally distributed (with 95% within range) and increase with well depth
cat("\tAssigning well capital expenses\n\t")
setorder(wells, depth)
wells[, "capExMM":= 0]
while (min(wells$capExMM) <= 0) {
    wells[area=="Eagle Ford",       "capExMM":= sort(rnorm(.N, (9.6 + 5.9)/2, (9.6 - 5.9)/1.282/2))]
    wells[area=="Delaware Basin",   "capExMM":= sort(rnorm(.N, (8.5 + 5.0)/2, (8.5 - 5.0)/1.282/2))]
    wells[area=="Midland Basin",    "capExMM":= sort(rnorm(.N, (8.6 + 5.5)/2, (8.6 - 5.5)/1.282/2))]
    # only the mean (2.5) is given for Spraberry. Assume a coefficient of variation of 0.2
    wells[area=="Spraberry",        "capExMM":= sort(rnorm(.N, 2.5, 0.5))]
}

# Lease capital expenditure is the sum of well costs (in millions of dollars)
leases_full[wells[, .(sum(capExMM), .N), by=.(DISTRICT_NO, LEASE_NO)], on=c("DISTRICT_NO", "LEASE_NO"),
                c("capEx", "N"):= .(V1 * 10^6, N)]

# Each gas lease should only have 1 well
leases_full <- leases_full[!(OIL_GAS_CODE=="G" & N>1)]
# Drop outlier oil leases
leases_full <- leases_full[!(OIL_GAS_CODE=="O" & N>quantile(N[OIL_GAS_CODE=="O"], 0.99))]
# Drop leases that appear to be flaring without any production
leases_full <- leases_full[!(gas_MCF>0 & (flared_MCF / gas_MCF)>0.25 & cond_BBL / (gas_MCF/6)<1)]

# Estimate operating expenses by lease (excludes natural gas liquids)
# base (pBOE):  Water, General & Administrative, Lease Operating Expenses, (ordered by productivity)
#  values estimated from [US EIA, 2016](zotero://select/items/0_EJYISQT4)
#  using [Webplotdigitizer](zotero://select/items/0_UW7H7HAP)
cat("\tAssigning lease operating expenses per barrel of oil equivalent\n\t")
leases_full[, "BOE":= oil_BBL + (gas_MCF + csgd_MCF - flared_MCF)/6]
setorder(leases_full, -BOE)
leases_full[, "opEx_pBOE":= 0]
while (min(leases_full$opEx_pBOE) <= 0) {
    leases_full[area=="Eagle Ford" & oil_BBL>0,                 "opEx_pBOE":=                             # oil
                                                                sort(rnorm(.N, (15.2+9.3)/2, (15.2-9.3)/4))]
    leases_full[area=="Eagle Ford" & gas_MCF>0 & cond_BBL>0,    "opEx_pBOE":=                             # wet gas
                                                                sort(rnorm(.N, (13.5+6.7)/2, (13.5-6.7)/4))]
    leases_full[area=="Eagle Ford" & gas_MCF>0 & cond_BBL==0,   "opEx_pBOE":=                             # dry gas
                                                                sort(rnorm(.N, (10.3+5.3)/2, (10.3-5.3)/4))]
    leases_full[area=="Delaware Basin",                         "opEx_pBOE":=
                                                                sort(rnorm(.N, (16.1+7.7)/2, (16.1-7.7)/4))]
    leases_full[area %in% c("Midland Basin","Spraberry"),       "opEx_pBOE":=
                                                                sort(rnorm(.N, (16.1+7.9)/2, (16.1-7.9)/4))]
}
# Use the empirical BOEs sold to calculate the baseline operating cost
leases_full[, "opEx" := opEx_pBOE * BOE]

# oil (pBBL):   Short Transportation, Long Transportation (ordered by how oil moves & distance from crude pipelines)
cat("\tAssigning lease operating expenses per barrel of oil\n\t")
setorder(leases_full, -pipe_frac, -rail_frac, crude_dist)
leases_full[, "opEx_pBBL":= ifelse(oil_BBL>0, 0, NA)]
while (min(leases_full$opEx_pBBL, na.rm=TRUE) <= 0) {
    leases_full[area=="Eagle Ford" & oil_BBL>0,                 "opEx_pBBL":=
                                                                sort(rnorm(.N, (6+3.75)/2, (6-3.75)/4))]
    leases_full[area=="Delaware Basin" & oil_BBL>0,             "opEx_pBBL":=
                                                                sort(rnorm(.N, (16+4.25)/2, (16-4.25)/4))]
    leases_full[area %in% c("Midland Basin","Spraberry") & oil_BBL>0,"opEx_pBBL":=
                                                                sort(rnorm(.N, (15.5+4.25)/2, (15.5-4.25)/4))]
}
leases_full[is.na(opEx_pBBL), "opEx_pBBL":= 0]

# gas (pMCF):   Gathering & Transportation, Processing (ordered by % flared & inverse-square distance weighted capacity)
cat("\tAssigning lease operating expenses per thousand cubic feet of gas\n\t")
leases_full[gas_MCF+csgd_MCF>0, "percent_flared":=  round(flared_MCF / (gas_MCF+csgd_MCF), 2)]
setorder(leases_full, percent_flared, -gas_cap)
leases_full[, "opEx_pMCF":= ifelse(gas_MCF+csgd_MCF>0, 0, NA)]
while (min(leases_full$opEx_pMCF, na.rm=TRUE) <= 0) {
    leases_full[area=="Eagle Ford" & csgd_MCF>0,                "opEx_pMCF":=                             # oil
                                                                sort(rnorm(.N, (1.60+0.85)/2, (1.60-0.85)/4))]
    leases_full[area=="Eagle Ford" & gas_MCF>0 & cond_BBL>0,    "opEx_pMCF":=                             # wet gas
                                                                sort(rnorm(.N, (1.60+0.85)/2, (1.60-0.85)/4))]
    leases_full[area=="Eagle Ford" & gas_MCF>0 & cond_BBL==0,   "opEx_pMCF":=                             # dry gas
                                                                sort(rnorm(.N, (1.05+0.55)/2, (1.05-0.55)/4))]
    leases_full[area=="Delaware Basin" & gas_MCF+csgd_MCF>0,    "opEx_pMCF":=
                                                                sort(rnorm(.N, (2.35+0.85)/2, (2.35-0.85)/4))]
    leases_full[area %in% c("Midland Basin","Spraberry") & gas_MCF+csgd_MCF>0,
                                                                "opEx_pMCF":=
                                                                sort(rnorm(.N, (1.70+0.85)/2, (1.70-0.85)/4))]
}
leases_full[is.na(opEx_pMCF), "opEx_pMCF":= 0]


# consolidate leases in the same field with the same start & expiration date
cat("\tAggregating similar leases in the same field\n\t")
# leases_full[, "start":= replace(start, start<201001, 201001)]
leases <- leases_full[, c(lapply(.SD[,.(oil_BBL, cond_BBL, gas_MCF, csgd_MCF)], sum),
                          lapply(.SD[,.(total_oil_BBL, total_MCF, flared_MCF)], sum),
                          lapply(.SD[,.(capEx, opEx)], sum),
                          lapply(.SD[,.(opEx_pBBL)], weighted.mean, oil_BBL),
                          lapply(.SD[,.(opEx_pMCF)], weighted.mean, gas_MCF+csgd_MCF)),
                    by=.(start, expiration, area, DISTRICT_NO, FIELD_NO, OIL_GAS_CODE)]

# calculate lease lifetime in months
leases[, "lifetime":= .SD[, lapply(.(expiration, start), function(x) 12*trunc(x/100) + x %% 100)][, V1-V2]]
leases <- leases[!(lifetime<12 & expiration<max(expiration))]
#   for leases that are still operating, estimate a lifetime based on historical distribution
leases[expiration==max(expiration),
        "lifetime":= sapply(lifetime, function(x) leases[OIL_GAS_CODE==.BY & lifetime>x, sample(c(lifetime, x), 1)]),
        by=OIL_GAS_CODE]

leases[oil_BBL==0,          opEx_pBBL:= 0]
leases[gas_MCF+csgd_MCF==0, opEx_pMCF:= 0]

# apply a price index to convert from 2014 dollars to historical costs (which were mostly lower)
well_cost_index <- fread("./inputs/processed/well_cost_index.csv")

leases[well_cost_index[, cbind("date"=as.numeric(sprintf("%d%02d", year, 1:12)), .SD), by=year], on=c(start="date"),
        "capEx":= capEx * real_index_2014]
leases[substr(start, 1, 4) < min(well_cost_index$year),
        "capEx":= capEx * well_cost_index[which.min(year), real_index_2014]]

# Assign other lease attributes
leases[, "firmID":= NA_integer_]
leases[, c("t_found","t_switch"):= NA_integer_]
leases[, c("class","status"):= NA_character_]
leases[, "time":= Params$t0-1]

# calculate lease operating expenses
leases[, sprintf("opEx_%s", c("oil","csgd","gas")):= calc_opEx(.SD)]

leases[, "leaseID":= .I]
setkey(leases, leaseID)


# initialize firms
cat("Generating representative firms\n\t")
firms <- data.table("firmID"= 1:Params$nagents, key= "firmID",
                    # how much oil (BBL) and gas (MCF) does the firm produce each time step
                    "oil_output"= NA_real_, "oil_revenue"= NA_real_,
                    "gas_output"= NA_real_, "green_gas_output"= NA_real_, "gas_revenue"= NA_real_,
                    # Valuations; costs include Operating, Mitigation, Capital Expenditures
                    "cash"= NA_real_, "market_value"= NA_real_,
                    "cost_O"= NA_real_, "cost_M"= NA_real_, "cost_CE"= NA_real_, "sPressure"= NA_real_,
                    # activities: exploration, development; behaviors: flaring, mitigating, economizing, imitating
                    "activity"= NA_character_, "behavior"= NA_character_,
                    "time"= Params$t0-1)

# Assign firms maximum production capacity based on empirics (oil production is log-normally distributed)
market_shares <- fread("./inputs/processed/firm_market_shares.csv")

# assign oil leases to agents according to their total production
cat("\tAssigning oil leases to firms\n\t")

firms[, "production_BBL":= 0]
while(!between(sum(firms$production_BBL)/mean(market_shares[, sum(scaled_oil_BBL), by=.(CYCLE_YEAR, CYCLE_MONTH)]$V1), 0.8, 1.1)) {
    firms[, "production_BBL":= rlnorm(.N, mean(log(market_shares$scaled_oil_BBL)),
                                            sd(log(market_shares$scaled_oil_BBL)))]
}

for (ID in firms[order(production_BBL)]$firmID) {
    leases[is.na(firmID) & oil_BBL>0, "firmID":= replace(firmID, which.min(total_oil_BBL), ID)]

    rem_capacity <- firms[ID, production_BBL] - leases[firmID==ID, sum(total_oil_BBL)]
    while (rem_capacity - min(leases[is.na(firmID) & (oil_BBL>0)]$total_oil_BBL) > 0) {
        leases[sample(.N, 1, prob=is.na(firmID) & (oil_BBL>0) & (rem_capacity - total_oil_BBL > 0)), "firmID":= ID]
        rem_capacity <- firms[ID, production_BBL] - leases[firmID==ID, sum(total_oil_BBL)]
   }
}

# assign gas leases to agents according to their total production
cat("\tAssigning gas leases to firms\n\t")

firms[, "production_MCF":= 0]
while(!between(sum(firms$production_MCF)/mean(market_shares[, sum(scaled_gas_MCF), by=.(CYCLE_YEAR, CYCLE_MONTH)]$V1), 0.9, 1.1)) {
    firms[order(log(production_BBL) * runif(.N, 0.5, 1.5)),
            "production_MCF":= sort(rlnorm(.N, mean(log(market_shares[scaled_gas_MCF>0, scaled_gas_MCF])),
                                                sd(log(market_shares[scaled_gas_MCF>0, scaled_gas_MCF]))))]
    # a large fraction (~40%) of firms operate oil leases only
    firms[runif(.N) < market_shares[, sum(scaled_gas_MCF==0)/length(scaled_gas_MCF)], "production_MCF":= 0]
}

for (ID in firms[production_MCF>0][order(production_MCF)]$firmID) {
    leases[is.na(firmID) & gas_MCF>0, "firmID":= replace(firmID, which.min(total_MCF), ID)]

    rem_capacity <- firms[ID, production_MCF] - leases[firmID==ID & gas_MCF>0, sum(total_MCF)]
    while (rem_capacity - min(leases[is.na(firmID) & (gas_MCF>0)]$total_MCF) > 0) {
        leases[sample(.N, 1, prob=is.na(firmID) & (gas_MCF>0) & (rem_capacity - total_MCF > 0)), "firmID":= ID]
        rem_capacity <- firms[ID, production_MCF] - leases[firmID==ID & gas_MCF>0, sum(total_MCF)]
   }
}

leases[!is.na(firmID), "t_found":= Params$t0 - 1]
leases[!is.na(firmID), c("class", "status"):= .(ifelse(csgd_MCF>0, "underdeveloped", "developed"), "producing")]


# assign cash reserves based on CRSP data
cat("\tAssigning cash reserves to firms\n\t")
finances <- fread("./inputs/processed/firm_finances.csv")
firms[, "cash":= rlnorm(.N, mean(log(finances[CI>0, CI])), sd(log(finances[CI>0, CI])))]
firms[, c("sales","profit"):= 0]

# initially there is no social pressure
firms[, "sPressure":= 0]

# initially no firms are capturing casinghead gas
firms[leases[!is.na(firmID), .(sum(oil_BBL), sum(gas_MCF)), by=firmID], on="firmID",
        c("oil_output", "gas_output"):= .(V1, V2)]
firms[leases[, sum(opEx_oil + opEx_gas), by=firmID], on="firmID", "cost_O":= V1]

firms[leases[!is.na(firmID), sum(csgd_MCF), by=firmID], on="firmID",
        "behavior":= ifelse(V1/oil_output > Params$threshold, "flaring", "economizing")]
firms[, c("cost_M", "green_gas_output"):= 0]
firms[, c("oil_revenue", "gas_revenue"):= .(oil_output * Params$oil_price, gas_output*Params$market_price_dirty)]

firms[, "market_value":= (oil_revenue + gas_revenue - cost_O)]

# generate validation report for this initialization
cat("Writing validation report\n")
rmarkdown::render("flaringABM_validation_init.Rmd", "html_document",
                    sprintf("outputs/validation/init_%s.html", jobID), quiet=TRUE)

# done
cat("Cleaning up\n\t")
rm(wells, leases_full, ID, market_shares, rem_capacity, finances)

cat(gsub("Time difference of", "Initialization complete in", capture.output(Sys.time() - init_time)), "\n")
